---
title: "GEN 711 Lab"
author: 
date: "Spring 2021"
output: html_document
---

<style type="text/css">

h1.title {
  font-size: 45px;
  color: Black;
  text-align: center;
}
h4.author { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  font-family: "Lucida Console", monospace;
  color: Black;
  text-align: center;
}
h4.date { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Lucida Console", monospace;
  color: Black;
  text-align: center;
</style>
</script>
<div class="row">
<div class="col-xs-12 col-sm-9 text-left">
<br/>

***

### __Lab Schedule__
__Week 1__</br>
- Sign up for an XSEDE account [here](https://www.xsede.org/web/xup/my-xsede?p_p_id=58&p_p_lifecycle=0&p_p_state=maximized&p_p_mode=view&_58_struts_action=%2Flogin%2Fcreate_account)</br>
- Download putty terminal (for windows machines only!) [here](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)</br>
- [Command line bootcamp](http://rik.smith-unna.com/command_line_bootcamp/): You can (and should) be working on this from you personal laptop.</br>

__Week 2__</br>
- Log in to [Jetstream](https://use.jetstream-cloud.org/). Here is some [info about it](https://iujetstream.atlassian.net/wiki/spaces/JWT/pages/17465367/System+Overview).</br>
- [Setting up your Jetstream VM](usingssh.html) for mac users</br>
- [Setting up your Jetstream VM](usingssh_windows.html) for windows users</br>
- [Launch a Jetstream instance](jetstream.html)</br>
- [Connect to a Jetstream instance](connect.html)</br>

__Week 3__</br>
- [Command Line BLAST](lab1_blast.html)</br>

__Week 4__</br>
- [Use a HMM to identify unknown sequences](hmmer.html)</br>

__Week 5__ </br>
- [Trimming fastQ files](trimming.html)</br>
- [Download notrim.zip](lab5_figs/notrim.zip)</br>
- [Download p2trim.zip](lab5_figs/p2trim.zip)</br>
- [Download p10trim.zip](lab5_figs/p10trim.zip)</br>
- [Download p30trim.zip](lab5_figs/p30trim.zip)</br>

__Week 6__ </br>
- [Mapping read data](mapping.html)</br>

***
### __Practice Exams__</br>
- Practice Exam1 [A](lab_exam1.html)
- Practice Exam1 [B](lab_exam1a.html)
- Practice Exam1 [C](lab_exam1b.html)
- Practice Exam1 [D](lab_exam1c.html)

***

__Week 8__</br>
- [genome assembly](bacterial_assembly.html)</br>

### __ADDITIONAL RESOURCES:__

- [Canvas](https://mycourses.unh.edu)

- [Github](https://github.com/macmanes/GEN711_S21)

- [Summer Workshops](http://angus.readthedocs.org/en/2014)

- [More Summer Workshops](http://angus.readthedocs.org/en/2015)

- [Helpful online book](https://open.oregonstate.education/computationalbiology/)

